import React from 'react';
import ImageFilter from './image-filter';

const filters = {
  CIBoxBlur: ['radius'],
  CIDiscBlur: ['radius'],
  CIGaussianBlur: ['radius'],
  // CIMaskedVariableBlur: ['radius', 'mask'],
  CIMedianFilter: [],
  CIMotionBlur: ['radius', 'angle'],
  CINoiseReduction: ['noiseLevel', 'sharpness'],
  CIZoomBlur: ['center', 'amount'],
  // CIColorClamp,
  CIColorControls: ['saturation', 'brightness', 'contrast']
  // CIColorMatrix,
  // CIColorPolynomial,
  // CIExposureAdjust,
  // CIGammaAdjust,
  // CIHueAdjust,
  // CILinearToSRGBToneCurve,
  // CISRGBToneCurveToLinear,
  // CITemperatureAndTint,
  // CIToneCurve,
  // CIVibrance,
  // CIWhitePointAdjust,
  // CIColorCrossPolynomial,
  // CIColorCube,
  // CIColorCubeWithColorSpace,
  // CIColorInvert,
  // CIColorMap,
  // CIColorMonochrome,
  // CIColorPosterize,
  // CIFalseColor,
  // CIMaskToAlpha,
  // CIMaximumComponent,
  // CIMinimumComponent,
  // CIPhotoEffectChrome,
  // CIPhotoEffectFade,
  // CIPhotoEffectInstant,
  // CIPhotoEffectMono,
  // CIPhotoEffectNoir,
  // CIPhotoEffectProcess,
  // CIPhotoEffectTonal,
  // CIPhotoEffectTransfer,
  // CISepiaTone,
  // CIVignette,
  // CIVignetteEffect,
  // CIAdditionCompositing,
  // CIColorBlendMode,
  // CIColorBurnBlendMode,
  // CIColorDodgeBlendMode,
  // CIDarkenBlendMode,
  // CIDifferenceBlendMode,
  // CIDivideBlendMode,
  // CIExclusionBlendMode,
  // CIHardLightBlendMode,
  // CIHueBlendMode,
  // CILightenBlendMode,
  // CILinearBurnBlendMode,
  // CILinearDodgeBlendMode,
  // CILuminosityBlendMode,
  // CIMaximumCompositing,
  // CIMinimumCompositing,
  // CIMultiplyBlendMode,
  // CIMultiplyCompositing,
  // CIOverlayBlendMode,
  // CIPinLightBlendMode,
  // CISaturationBlendMode,
  // CIScreenBlendMode,
  // CISoftLightBlendMode,
  // CISourceAtopCompositing,
  // CISourceInCompositing,
  // CISourceOutCompositing,
  // CISourceOverCompositing,
  // CISubtractBlendMode,
  // CIBumpDistortion,
  // CIBumpDistortionLinear,
  // CICircleSplashDistortion,
  // CICircularWrap,
  // CIDroste,
  // CIDisplacementDistortion,
  // CIGlassDistortion,
  // CIGlassLozenge,
  // CIHoleDistortion,
  // CILightTunnel,
  // CIPinchDistortion,
  // CIStretchCrop,
  // CITorusLensDistortion,
  // CITwirlDistortion,
  // CIVortexDistortion,
  // CIAztecCodeGenerator,
  // CICheckerboardGenerator,
  // CICode128BarcodeGenerator,
  // CIConstantColorGenerator,
  // CILenticularHaloGenerator,
  // CIPDF417BarcodeGenerator,
  // CIQRCodeGenerator,
  // CIRandomGenerator,
  // CIStarShineGenerator,
  // CIStripesGenerator,
  // CISunbeamsGenerator,
  // CIAffineTransform,
  // CICrop,
  // CILanczosScaleTransform,
  // CIPerspectiveCorrection,
  // CIPerspectiveTransform,
  // CIPerspectiveTransformWithExtent,
  // CIStraightenFilter,
  // CIGaussianGradient,
  // CILinearGradient,
  // CIRadialGradient,
  // CISmoothLinearGradient,
  // CICircularScreen,
  // CICMYKHalftone,
  // CIDotScreen,
  // CIHatchedScreen,
  // CILineScreen,
  // CIAreaAverage,
  // CIAreaHistogram,
  // CIRowAverage,
  // CIColumnAverage,
  // CIHistogramDisplayFilter,
  // CIAreaMaximum,
  // CIAreaMinimum,
  // CIAreaMaximumAlpha,
  // CIAreaMinimumAlpha,
  // CISharpenLuminance,
  // CIUnsharpMask,
  // CIBlendWithAlphaMask,
  // CIBlendWithMask,
  // CIBloom,
  // CIComicEffect,
  // CIConvolution3X3,
  // CIConvolution5X5,
  // CIConvolution7X7,
  // CIConvolution9Horizontal,
  // CIConvolution9Vertical,
  // CICrystallize,
  // CIDepthOfField,
  // CIEdges,
  // CIEdgeWork,
  // CIGloom,
  // CIHeightFieldFromMask,
  // CIHexagonalPixellate,
  // CIHighlightShadowAdjust,
  // CILineOverlay,
  // CIPixellate,
  // CIPointillize,
  // CIShadedMaterial,
  // CISpotColor,
  // CISpotLight,
  // CIAffineClamp,
  // CIAffineTile,
  // CIEightfoldReflectedTile,
  // CIFourfoldReflectedTile,
  // CIFourfoldRotatedTile,
  // CIFourfoldTranslatedTile,
  // CIGlideReflectedTile,
  // CIKaleidoscope,
  // CIOpTile,
  // CIParallelogramTile,
  // CIPerspectiveTile,
  // CISixfoldReflectedTile,
  // CISixfoldRotatedTile,
  // CITriangleKaleidoscope,
  // CITriangleTile,
  // CITwelvefoldReflectedTile,
  // CIAccordionFoldTransition,
  // CIBarsSwipeTransition,
  // CICopyMachineTransition,
  // CIDisintegrateWithMaskTransition,
  // CIDissolveTransition,
  // CIFlashTransition,
  // CIModTransition,
  // CIPageCurlTransition,
  // CIPageCurlWithShadowTransition,
  // CIRippleTransition,
  // CISwipeTransition
};

const createImageNativeFilter = (name, paramNames) => ({ children, ...restProps }) => (
  <ImageFilter
    name={name}
    paramNames={paramNames}
    {...restProps}
  >
    {children}
  </ImageFilter>
);

export default Object.keys(filters).reduce(
  (acc, name) => {
    acc[`Image${name.slice(2)}Filter`] = createImageNativeFilter(name, filters[name]);
    return acc;
  },
  {}
);

